config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/about',              to: 'static_pages#about'
  get    '/applications',       to: 'static_pages#home'
  get    '/contact',            to: 'static_pages#contact'
  get    '/faq',                to: 'static_pages#faq'
  get    '/help',               to: 'static_pages#help'
  get    '/home',               to: 'static_pages#home'
  get    '/login',              to: 'sessions#new'
  get    '/signup',             to: 'users#new'
  get    '/users',              to: 'users#index'
  
  post   '/account_activation', to: 'account_activation#edit'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  
  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets,    only: [:new, :create, :edit, :update]
  resources :skills,             only: [:create, :destroy]
  resources :experiences,        only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def faq
  end

  def about
  end
  
  def home
    if logged_in?
      @skill = current_user.skills.build
      @skill_items = current_user.skills_feed.paginate(page: params[:page], per_page: 5)
      @experience = current_user.experiences.build
      @experience_items = current_user.experiences_feed.paginate(page: params[:page], per_page: 5)
    end
  end
  
  def help
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about">
<h1>About Us</h1>
<p>
KinNect is an early stage startup dedicated to connecting formerly incarcerated individuals with employment opportunities. Our goal is to help the 600,000+ individuals exiting incarceration and returning to the workforce annually by finding them meaningful and financially sustainable employment that reduces their likelihood to become entangled with the criminal (in)justice system and provides the foundation to thrive within a community, increasing stability for a successful reentry. We are working to build a marketplace of jobs for this population while addressing the common pitfalls in applying for jobs, like a resume generator and an employer toolkit. KinNect’s founder and CEO, Thanisha Pariage, is a former public defender and currently the Recruiting and Hiring Manager at Bronx Defenders. She recently graduated as the David Bohnett fellow at NYU Wagner School of Public Service. The team includes William Coit- NYU Masters student and COO. The KinNect team has both personal and professional experience addressing this challenge.
</p>

<h1>Employer</h1>
<p>
Employers on our platform will be considered “socially conscious”. In the current political climate, there is a need to be more progressive and mindful of the oppressed. For employers, they will have the understanding that everyone on the platform is formerly incarcerated. Thus, they can choose if they want to participate or not and doesn’t signal anyone out that isn’t on the platform. For example, this model would not work on indeed or linkedin because employers cannot opt out of hiring the FIP as it’s illegal. With a model like that, you’ll have a bunch of employers who “say” they hire in an equitable manner but doesn’t actually engage the FIP. This is why KinNect is so important as it’s a commitment to hiring FIP as the only user is FIP. We envision creating a toolkit of materials for employers on how to hire this sensitive population and benefits of hiring them. Materials will include interviewing techniques and thoughtful ways to recruit and onboard neither a DEI lens. We will also provide the information on how to take advantage of all the government incentives.
<br/>
We also envision having a rating system. Based on how many FIP you interview and hire, you will receive a KinNect rating of 1-5 to publicize the good work you’ve been doing. (This can be built out more. Based on clicks or how many applications they open and what not)
</p>

<h1>Job Seeker</h1>
<p>
The user will be able to use KinNect inside and out of prison. They will have the ability to make a profile, generate a simplistic resume, and view interactive videos to get them “job ready”. In addition tools will be provided to get the documentation they need for applying to jobs like SS card and ID.
</p>

<h1>Background</h1>
<p>
Formerly Incarcerated Individuals (FII) face a host of challenges when re-entering the community. Within three years of being released, two-thirds of FII are arrested again. Approximately 600,000 individuals are returning home each year and the unemployment rate amongst these individuals are as high as 60%.
  <br/>
Many studies find that employment earnings are reduced by the stain of incarceration, in relation to what it would be absent incarceration. In particular, earnings are reduced anywhere from 10-30%. To place and retain an individual in a job costs approximately $5,000. While cost per formerly incarcerated individual varies from state to state, NYC costs are approximately $68,000 per year to house a formerly incarcerated individual. Securing employment for 100 FII would increase their income and tax contributions by $1.9 million, saving over $6 million annually by keeping this number of individuals out of prison. 
   <br/>
There are many causes of unemployment amongst the FII. Stigma is the driving force of unemployment within the formerly incarcerated community. Also, the cost of being a person of color and trying to find a job is also barrier within its own. In addition, FII often have challenging attributes like limited education and work histories, making them less appealing to employers. Further, competing demands from mandatory programming through parole and probation can be burdensome. 
   <br/>
    Understandably, tangibility is also an issue within the formerly incarcerated job market. Based on consumer based discovery, FII fail to apply to many jobs because they have deemed them “unrealistic”. Stigma has destroyed confidence resulting in underapplying in certain markets. 
    <br/>
    KinNect is formed within a current gap in reentry services as they are having issues retaining this target demographic and maintaining partnerships with employers committed to fulfilling an obligation to proactively hire FII. The truth is, the millennial demographic isn’t interested in schleping to a reentry space, and they currently do everything through tech. Currently, there is an assumption that this population needs one on one care, we propose that one on one care can still happen through tools on KinNect.
    <br/>
    KinNect also sets itself apart because, while we cater to FII, we also realize the importance of tangibility. With that, we are creating an environment of socially conscious employers because we recognize that the work that needs to be done, need not only be done on behalf of FII. Employers too are the problem. They need to consciously make the decision to hire FII. Once they make the commitment to KinNect, they will be provided the education, resources, and tools to hire and host FII.
    <br/>
    Current models have a huge opportunity gap, either because they are not progressive enough and are satisfied with the market they are serving or they have have not taken the time to engage the population they are trying to serve. Through consumer based discovery, we learned that organizations like Getting Out Staying Out (GOSO) don’t have the capacity to maintain employer relationships thus utilize subsidized employments for their clients to receive work training, often not resulting in full time employment. Similarly, Center for Employment Opportunity and Exodus have issues retaining their younger population and maintaining employer relationships as well. Newer organizations like When People Work fail to provide FII with the resources needed to empower themselves and maximize their success. They fail to realize that FII consistently have insufficient application materials like a resume or documents to fulfill the I-9 process. 
</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/faq.html.erb
<% provide(:title, "FAQ") %>
<h1>FAQ</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="skill_form">
        <%= render 'shared/skill_form' %>
      </section>
      <section class="experience_form">
        <%= render 'shared/experience_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>CV Feed</h3>
      <%= render 'shared/cv_feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to </h1><h1>Kinnect Careers</h1>
    <h2>Connecting employers and job seekers</h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <!-- TODO: Add LOGO!
      link_to image_tag("kinnect_logo.svg", alt: "Kinnect Careers Logo", width: "200"), home_url
    -->
  </div>
<% end %>